# Generated by Django 5.2.5 on 2025-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
